version: '2'

networks:
  my-network:
    driver: bridge
services:
  pgpool:
    image: bitnami/pgpool:4
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local